// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd_uLzdTu13Went0XKQkmrlJ_AGwnIRuM',
    appId: '1:241750536649:web:888e957056f46430617818',
    messagingSenderId: '241750536649',
    projectId: 'eservicenotifications-78b8b',
    authDomain: 'eservicenotifications-78b8b.firebaseapp.com',
    storageBucket: 'eservicenotifications-78b8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj3vrAqubLO7hrJogzv179bPTkiJtTS6I',
    appId: '1:241750536649:android:2d6c3182f0d324d3617818',
    messagingSenderId: '241750536649',
    projectId: 'eservicenotifications-78b8b',
    storageBucket: 'eservicenotifications-78b8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeOieJZAMfy41uveyJP8bWOyVIO7ghzP8',
    appId: '1:241750536649:ios:5d42a8d7fed01b2b617818',
    messagingSenderId: '241750536649',
    projectId: 'eservicenotifications-78b8b',
    storageBucket: 'eservicenotifications-78b8b.appspot.com',
    iosBundleId: 'gov.lekbeshimun.lekbeshimuneservices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeOieJZAMfy41uveyJP8bWOyVIO7ghzP8',
    appId: '1:241750536649:ios:5d42a8d7fed01b2b617818',
    messagingSenderId: '241750536649',
    projectId: 'eservicenotifications-78b8b',
    storageBucket: 'eservicenotifications-78b8b.appspot.com',
    iosBundleId: 'gov.lekbeshimun.lekbeshimuneservices',
  );
}
